// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrvoimthsdmossgnjcen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indydm9pbXRoc2Rtb3NzZ25qY2VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MjcxODEsImV4cCI6MjA3NTUwMzE4MX0.j2nBwUikdrHsI0iMO03__z1ffwJEQKE_QuY-LC9XCb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});